"""asiento y calidad en boleto

Revision ID: 62edb79b3cf7
Revises: cdc8e7ff73e7
Create Date: 2026-06-18 17:33:22.330461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62edb79b3cf7'
down_revision = 'cdc8e7ff73e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boleto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asiento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('calidad', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boleto', schema=None) as batch_op:
        batch_op.drop_column('calidad')
        batch_op.drop_column('asiento')

    # ### end Alembic commands ###
