"""añadir imagen a peliculas

Revision ID: 6679b8e2cd9b
Revises: 62edb79b3cf7
Create Date: 2026-06-19 19:31:52.095845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6679b8e2cd9b'
down_revision = '62edb79b3cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
