"""Creación de las 8 tablas del proyecto

Revision ID: cdc8e7ff73e7
Revises: 
Create Date: 2026-06-14 16:08:52.709617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc8e7ff73e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pelicula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('sinopsis', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_sala', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('funcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['pelicula.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('funcion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcion_id'], ['funcion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boleto')
    op.drop_table('funcion')
    op.drop_table('user')
    op.drop_table('sala')
    op.drop_table('pelicula')
    op.drop_table('sucursal')
    op.drop_table('role')
    op.drop_table('genero')
    # ### end Alembic commands ###
